# Server
server:
  port: 8701

# dubbo
dubbo:
  application:
    name: dubbo-provider
  registry:
    address: zookeeper://127.0.0.1:2181?client=curator
  protocol:
    name: dubbo
    port: 20880
  scan: org.jim.dubbo.service